<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Folio', 'doctrine');

/**
 * BaseFolio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idfolio
 * @property integer $numero_actual
 * @property integer $anho_actual
 * @property integer $id_tipo_documento
 * 
 * @method integer getIdfolio()           Returns the current record's "idfolio" value
 * @method integer getNumeroActual()      Returns the current record's "numero_actual" value
 * @method integer getAnhoActual()        Returns the current record's "anho_actual" value
 * @method integer getIdTipoDocumento()   Returns the current record's "id_tipo_documento" value
 * @method Folio   setIdfolio()           Sets the current record's "idfolio" value
 * @method Folio   setNumeroActual()      Sets the current record's "numero_actual" value
 * @method Folio   setAnhoActual()        Sets the current record's "anho_actual" value
 * @method Folio   setIdTipoDocumento()   Sets the current record's "id_tipo_documento" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFolio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('folio');
        $this->hasColumn('idfolio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('numero_actual', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('anho_actual', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_documento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}