<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoControlProyecto', 'doctrine');

/**
 * BaseTipoControlProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo_control
 * @property string $descripcion
 * @property Doctrine_Collection $Proyecto
 * 
 * @method integer             getIdTipoControl()   Returns the current record's "id_tipo_control" value
 * @method string              getDescripcion()     Returns the current record's "descripcion" value
 * @method Doctrine_Collection getProyecto()        Returns the current record's "Proyecto" collection
 * @method TipoControlProyecto setIdTipoControl()   Sets the current record's "id_tipo_control" value
 * @method TipoControlProyecto setDescripcion()     Sets the current record's "descripcion" value
 * @method TipoControlProyecto setProyecto()        Sets the current record's "Proyecto" collection
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoControlProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_control_proyecto');
        $this->hasColumn('id_tipo_control', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Proyecto', array(
             'local' => 'id_tipo_control',
             'foreign' => 'id_tipo_control_tec'));
    }
}