<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RptGeneralProyecto', 'doctrine');

/**
 * BaseRptGeneralProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_proyecto
 * @property string $sigla_contable
 * @property integer $monto_total
 * @property integer $monto_ing
 * @property integer $monto_egre
 * @property integer $ing_reales
 * @property integer $gas_reales
 * @property integer $compromisos
 * @property integer $ing_reales_us
 * @property integer $gas_reales_us
 * @property integer $compromisos_us
 * @property integer $numcontable
 * @property integer $id_moneda
 * @property decimal $porc_overhead
 * @property string $grupo_proyecto
 * @property date $fec_inicio_proy
 * @property date $fec_termino_proy
 * @property string $moneda
 * @property string $pais
 * @property decimal $ppto_ovh
 * @property decimal $gasto_ovhpesos
 * @property decimal $gasto_ovhus
 * 
 * @method integer            getId()               Returns the current record's "id" value
 * @method integer            getIdProyecto()       Returns the current record's "id_proyecto" value
 * @method string             getSiglaContable()    Returns the current record's "sigla_contable" value
 * @method integer            getMontoTotal()       Returns the current record's "monto_total" value
 * @method integer            getMontoIng()         Returns the current record's "monto_ing" value
 * @method integer            getMontoEgre()        Returns the current record's "monto_egre" value
 * @method integer            getIngReales()        Returns the current record's "ing_reales" value
 * @method integer            getGasReales()        Returns the current record's "gas_reales" value
 * @method integer            getCompromisos()      Returns the current record's "compromisos" value
 * @method integer            getIngRealesUs()      Returns the current record's "ing_reales_us" value
 * @method integer            getGasRealesUs()      Returns the current record's "gas_reales_us" value
 * @method integer            getCompromisosUs()    Returns the current record's "compromisos_us" value
 * @method integer            getNumcontable()      Returns the current record's "numcontable" value
 * @method integer            getIdMoneda()         Returns the current record's "id_moneda" value
 * @method decimal            getPorcOverhead()     Returns the current record's "porc_overhead" value
 * @method string             getGrupoProyecto()    Returns the current record's "grupo_proyecto" value
 * @method date               getFecInicioProy()    Returns the current record's "fec_inicio_proy" value
 * @method date               getFecTerminoProy()   Returns the current record's "fec_termino_proy" value
 * @method string             getMoneda()           Returns the current record's "moneda" value
 * @method string             getPais()             Returns the current record's "pais" value
 * @method decimal            getPptoOvh()          Returns the current record's "ppto_ovh" value
 * @method decimal            getGastoOvhpesos()    Returns the current record's "gasto_ovhpesos" value
 * @method decimal            getGastoOvhus()       Returns the current record's "gasto_ovhus" value
 * @method RptGeneralProyecto setId()               Sets the current record's "id" value
 * @method RptGeneralProyecto setIdProyecto()       Sets the current record's "id_proyecto" value
 * @method RptGeneralProyecto setSiglaContable()    Sets the current record's "sigla_contable" value
 * @method RptGeneralProyecto setMontoTotal()       Sets the current record's "monto_total" value
 * @method RptGeneralProyecto setMontoIng()         Sets the current record's "monto_ing" value
 * @method RptGeneralProyecto setMontoEgre()        Sets the current record's "monto_egre" value
 * @method RptGeneralProyecto setIngReales()        Sets the current record's "ing_reales" value
 * @method RptGeneralProyecto setGasReales()        Sets the current record's "gas_reales" value
 * @method RptGeneralProyecto setCompromisos()      Sets the current record's "compromisos" value
 * @method RptGeneralProyecto setIngRealesUs()      Sets the current record's "ing_reales_us" value
 * @method RptGeneralProyecto setGasRealesUs()      Sets the current record's "gas_reales_us" value
 * @method RptGeneralProyecto setCompromisosUs()    Sets the current record's "compromisos_us" value
 * @method RptGeneralProyecto setNumcontable()      Sets the current record's "numcontable" value
 * @method RptGeneralProyecto setIdMoneda()         Sets the current record's "id_moneda" value
 * @method RptGeneralProyecto setPorcOverhead()     Sets the current record's "porc_overhead" value
 * @method RptGeneralProyecto setGrupoProyecto()    Sets the current record's "grupo_proyecto" value
 * @method RptGeneralProyecto setFecInicioProy()    Sets the current record's "fec_inicio_proy" value
 * @method RptGeneralProyecto setFecTerminoProy()   Sets the current record's "fec_termino_proy" value
 * @method RptGeneralProyecto setMoneda()           Sets the current record's "moneda" value
 * @method RptGeneralProyecto setPais()             Sets the current record's "pais" value
 * @method RptGeneralProyecto setPptoOvh()          Sets the current record's "ppto_ovh" value
 * @method RptGeneralProyecto setGastoOvhpesos()    Sets the current record's "gasto_ovhpesos" value
 * @method RptGeneralProyecto setGastoOvhus()       Sets the current record's "gasto_ovhus" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRptGeneralProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rpt_general_proyecto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sigla_contable', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('monto_total', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monto_ing', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monto_egre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ing_reales', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('gas_reales', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('compromisos', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ing_reales_us', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('gas_reales_us', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('compromisos_us', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numcontable', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_moneda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('porc_overhead', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('grupo_proyecto', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fec_inicio_proy', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fec_termino_proy', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('moneda', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('pais', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ppto_ovh', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('gasto_ovhpesos', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('gasto_ovhus', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}