<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PerfilAccion', 'doctrine');

/**
 * BasePerfilAccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_perfil
 * @property integer $id_accion
 * @property Accion $Accion
 * @property Perfil $Perfil
 * 
 * @method integer      getIdPerfil()  Returns the current record's "id_perfil" value
 * @method integer      getIdAccion()  Returns the current record's "id_accion" value
 * @method Accion       getAccion()    Returns the current record's "Accion" value
 * @method Perfil       getPerfil()    Returns the current record's "Perfil" value
 * @method PerfilAccion setIdPerfil()  Sets the current record's "id_perfil" value
 * @method PerfilAccion setIdAccion()  Sets the current record's "id_accion" value
 * @method PerfilAccion setAccion()    Sets the current record's "Accion" value
 * @method PerfilAccion setPerfil()    Sets the current record's "Perfil" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfilAccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil_accion');
        $this->hasColumn('id_perfil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_accion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Accion', array(
             'local' => 'id_accion',
             'foreign' => 'id_accion'));

        $this->hasOne('Perfil', array(
             'local' => 'id_perfil',
             'foreign' => 'id_perfil'));
    }
}