<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parametro', 'doctrine');

/**
 * BaseParametro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_parametro
 * @property integer $id_hijo
 * @property integer $id_padre
 * @property string $descripcion
 * 
 * @method integer   getIdParametro()  Returns the current record's "id_parametro" value
 * @method integer   getIdHijo()       Returns the current record's "id_hijo" value
 * @method integer   getIdPadre()      Returns the current record's "id_padre" value
 * @method string    getDescripcion()  Returns the current record's "descripcion" value
 * @method Parametro setIdParametro()  Sets the current record's "id_parametro" value
 * @method Parametro setIdHijo()       Sets the current record's "id_hijo" value
 * @method Parametro setIdPadre()      Sets the current record's "id_padre" value
 * @method Parametro setDescripcion()  Sets the current record's "descripcion" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParametro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parametro');
        $this->hasColumn('id_parametro', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_hijo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_padre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}