<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Moneda', 'doctrine');

/**
 * BaseMoneda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_moneda
 * @property string $descripcion
 * @property string $codigo
 * @property Doctrine_Collection $Proyecto
 * 
 * @method integer             getIdMoneda()    Returns the current record's "id_moneda" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method string              getCodigo()      Returns the current record's "codigo" value
 * @method Doctrine_Collection getProyecto()    Returns the current record's "Proyecto" collection
 * @method Moneda              setIdMoneda()    Sets the current record's "id_moneda" value
 * @method Moneda              setDescripcion() Sets the current record's "descripcion" value
 * @method Moneda              setCodigo()      Sets the current record's "codigo" value
 * @method Moneda              setProyecto()    Sets the current record's "Proyecto" collection
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMoneda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('moneda');
        $this->hasColumn('id_moneda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('codigo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Proyecto', array(
             'local' => 'id_moneda',
             'foreign' => 'id_moneda'));
    }
}