<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Proveedor', 'doctrine');

/**
 * BaseProveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_proveedor
 * @property string $rut_proveedor
 * @property string $razon_social
 * @property string $telefono
 * @property string $email
 * 
 * @method integer   getIdProveedor()   Returns the current record's "id_proveedor" value
 * @method string    getRutProveedor()  Returns the current record's "rut_proveedor" value
 * @method string    getRazonSocial()   Returns the current record's "razon_social" value
 * @method string    getTelefono()      Returns the current record's "telefono" value
 * @method string    getEmail()         Returns the current record's "email" value
 * @method Proveedor setIdProveedor()   Sets the current record's "id_proveedor" value
 * @method Proveedor setRutProveedor()  Sets the current record's "rut_proveedor" value
 * @method Proveedor setRazonSocial()   Sets the current record's "razon_social" value
 * @method Proveedor setTelefono()      Sets the current record's "telefono" value
 * @method Proveedor setEmail()         Sets the current record's "email" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProveedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proveedor');
        $this->hasColumn('id_proveedor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rut_proveedor', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('razon_social', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('telefono', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}