<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Accion', 'doctrine');

/**
 * BaseAccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_accion
 * @property string $nombre
 * @property integer $id_estado_inicial
 * @property integer $id_estado_final
 * @property string $pregunta
 * @property EstadoProyecto $EstadoProyecto
 * @property EstadoProyecto $EstadoProyecto_2
 * @property Doctrine_Collection $Bitacora
 * @property Doctrine_Collection $Inbox
 * @property Doctrine_Collection $PerfilAccion
 * 
 * @method integer             getIdAccion()          Returns the current record's "id_accion" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method integer             getIdEstadoInicial()   Returns the current record's "id_estado_inicial" value
 * @method integer             getIdEstadoFinal()     Returns the current record's "id_estado_final" value
 * @method string              getPregunta()          Returns the current record's "pregunta" value
 * @method EstadoProyecto      getEstadoProyecto()    Returns the current record's "EstadoProyecto" value
 * @method EstadoProyecto      getEstadoProyecto2()   Returns the current record's "EstadoProyecto_2" value
 * @method Doctrine_Collection getBitacora()          Returns the current record's "Bitacora" collection
 * @method Doctrine_Collection getInbox()             Returns the current record's "Inbox" collection
 * @method Doctrine_Collection getPerfilAccion()      Returns the current record's "PerfilAccion" collection
 * @method Accion              setIdAccion()          Sets the current record's "id_accion" value
 * @method Accion              setNombre()            Sets the current record's "nombre" value
 * @method Accion              setIdEstadoInicial()   Sets the current record's "id_estado_inicial" value
 * @method Accion              setIdEstadoFinal()     Sets the current record's "id_estado_final" value
 * @method Accion              setPregunta()          Sets the current record's "pregunta" value
 * @method Accion              setEstadoProyecto()    Sets the current record's "EstadoProyecto" value
 * @method Accion              setEstadoProyecto2()   Sets the current record's "EstadoProyecto_2" value
 * @method Accion              setBitacora()          Sets the current record's "Bitacora" collection
 * @method Accion              setInbox()             Sets the current record's "Inbox" collection
 * @method Accion              setPerfilAccion()      Sets the current record's "PerfilAccion" collection
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accion');
        $this->hasColumn('id_accion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_estado_inicial', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_estado_final', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pregunta', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EstadoProyecto', array(
             'local' => 'id_estado_inicial',
             'foreign' => 'id_estado_proyecto'));

        $this->hasOne('EstadoProyecto as EstadoProyecto_2', array(
             'local' => 'id_estado_final',
             'foreign' => 'id_estado_proyecto'));

        $this->hasMany('Bitacora', array(
             'local' => 'id_accion',
             'foreign' => 'id_accion'));

        $this->hasMany('Inbox', array(
             'local' => 'id_accion',
             'foreign' => 'id_accion'));

        $this->hasMany('PerfilAccion', array(
             'local' => 'id_accion',
             'foreign' => 'id_accion'));
    }
}