<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Inbox', 'doctrine');

/**
 * BaseInbox
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_inbox
 * @property integer $id_proyecto
 * @property integer $id_emisor
 * @property integer $id_destinatario
 * @property integer $id_accion
 * @property date $fecha_recepcion
 * @property date $fecha_despacho
 * @property string $unidad_origen
 * @property string $unidad_destino
 * @property integer $id_tipo_documento
 * @property integer $folio
 * @property integer $id_orden_pago
 * @property Accion $Accion
 * @property Proyecto $Proyecto
 * @property Usuario $Emisor
 * @property Usuario $Destinatario
 * 
 * @method integer  getIdInbox()           Returns the current record's "id_inbox" value
 * @method integer  getIdProyecto()        Returns the current record's "id_proyecto" value
 * @method integer  getIdEmisor()          Returns the current record's "id_emisor" value
 * @method integer  getIdDestinatario()    Returns the current record's "id_destinatario" value
 * @method integer  getIdAccion()          Returns the current record's "id_accion" value
 * @method date     getFechaRecepcion()    Returns the current record's "fecha_recepcion" value
 * @method date     getFechaDespacho()     Returns the current record's "fecha_despacho" value
 * @method string   getUnidadOrigen()      Returns the current record's "unidad_origen" value
 * @method string   getUnidadDestino()     Returns the current record's "unidad_destino" value
 * @method integer  getIdTipoDocumento()   Returns the current record's "id_tipo_documento" value
 * @method integer  getFolio()             Returns the current record's "folio" value
 * @method integer  getIdOrdenPago()       Returns the current record's "id_orden_pago" value
 * @method Accion   getAccion()            Returns the current record's "Accion" value
 * @method Proyecto getProyecto()          Returns the current record's "Proyecto" value
 * @method Usuario  getEmisor()            Returns the current record's "Emisor" value
 * @method Usuario  getDestinatario()      Returns the current record's "Destinatario" value
 * @method Inbox    setIdInbox()           Sets the current record's "id_inbox" value
 * @method Inbox    setIdProyecto()        Sets the current record's "id_proyecto" value
 * @method Inbox    setIdEmisor()          Sets the current record's "id_emisor" value
 * @method Inbox    setIdDestinatario()    Sets the current record's "id_destinatario" value
 * @method Inbox    setIdAccion()          Sets the current record's "id_accion" value
 * @method Inbox    setFechaRecepcion()    Sets the current record's "fecha_recepcion" value
 * @method Inbox    setFechaDespacho()     Sets the current record's "fecha_despacho" value
 * @method Inbox    setUnidadOrigen()      Sets the current record's "unidad_origen" value
 * @method Inbox    setUnidadDestino()     Sets the current record's "unidad_destino" value
 * @method Inbox    setIdTipoDocumento()   Sets the current record's "id_tipo_documento" value
 * @method Inbox    setFolio()             Sets the current record's "folio" value
 * @method Inbox    setIdOrdenPago()       Sets the current record's "id_orden_pago" value
 * @method Inbox    setAccion()            Sets the current record's "Accion" value
 * @method Inbox    setProyecto()          Sets the current record's "Proyecto" value
 * @method Inbox    setEmisor()            Sets the current record's "Emisor" value
 * @method Inbox    setDestinatario()      Sets the current record's "Destinatario" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInbox extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inbox');
        $this->hasColumn('id_inbox', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_emisor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_destinatario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_accion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_recepcion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_despacho', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('unidad_origen', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('unidad_destino', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_tipo_documento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('folio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_orden_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Accion', array(
             'local' => 'id_accion',
             'foreign' => 'id_accion'));

        $this->hasOne('Proyecto', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasOne('Usuario as Emisor', array(
             'local' => 'id_emisor',
             'foreign' => 'id_usuario'));

        $this->hasOne('Usuario as Destinatario', array(
             'local' => 'id_destinatario',
             'foreign' => 'id_usuario'));
    }
}