<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArchivoGastoPais', 'doctrine');

/**
 * BaseArchivoGastoPais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_archivo_gasto_pais
 * @property integer $id_usuario
 * @property string $nombre
 * @property string $ruta
 * @property timestamp $fecha
 * @property integer $vigente
 * @property Usuario $Usuario
 * @property Doctrine_Collection $GastoPais
 * 
 * @method integer             getIdArchivoGastoPais()    Returns the current record's "id_archivo_gasto_pais" value
 * @method integer             getIdUsuario()             Returns the current record's "id_usuario" value
 * @method string              getNombre()                Returns the current record's "nombre" value
 * @method string              getRuta()                  Returns the current record's "ruta" value
 * @method timestamp           getFecha()                 Returns the current record's "fecha" value
 * @method integer             getVigente()               Returns the current record's "vigente" value
 * @method Usuario             getUsuario()               Returns the current record's "Usuario" value
 * @method Doctrine_Collection getGastoPais()             Returns the current record's "GastoPais" collection
 * @method ArchivoGastoPais    setIdArchivoGastoPais()    Sets the current record's "id_archivo_gasto_pais" value
 * @method ArchivoGastoPais    setIdUsuario()             Sets the current record's "id_usuario" value
 * @method ArchivoGastoPais    setNombre()                Sets the current record's "nombre" value
 * @method ArchivoGastoPais    setRuta()                  Sets the current record's "ruta" value
 * @method ArchivoGastoPais    setFecha()                 Sets the current record's "fecha" value
 * @method ArchivoGastoPais    setVigente()               Sets the current record's "vigente" value
 * @method ArchivoGastoPais    setUsuario()               Sets the current record's "Usuario" value
 * @method ArchivoGastoPais    setGastoPais()             Sets the current record's "GastoPais" collection
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivoGastoPais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivo_gasto_pais');
        $this->hasColumn('id_archivo_gasto_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('ruta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('vigente', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario'));

        $this->hasMany('GastoPais', array(
             'local' => 'id_archivo_gasto_pais',
             'foreign' => 'id_archivo_gasto_pais'));
    }
}