<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Perfil', 'doctrine');

/**
 * BasePerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_perfil
 * @property string $descripcion
 * @property Doctrine_Collection $Grupo
 * @property Doctrine_Collection $PerfilAccion
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getIdPerfil()     Returns the current record's "id_perfil" value
 * @method string              getDescripcion()  Returns the current record's "descripcion" value
 * @method Doctrine_Collection getGrupo()        Returns the current record's "Grupo" collection
 * @method Doctrine_Collection getPerfilAccion() Returns the current record's "PerfilAccion" collection
 * @method Doctrine_Collection getUsuario()      Returns the current record's "Usuario" collection
 * @method Perfil              setIdPerfil()     Sets the current record's "id_perfil" value
 * @method Perfil              setDescripcion()  Sets the current record's "descripcion" value
 * @method Perfil              setGrupo()        Sets the current record's "Grupo" collection
 * @method Perfil              setPerfilAccion() Sets the current record's "PerfilAccion" collection
 * @method Perfil              setUsuario()      Sets the current record's "Usuario" collection
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil');
        $this->hasColumn('id_perfil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Grupo', array(
             'local' => 'id_perfil',
             'foreign' => 'id_perfil'));

        $this->hasMany('PerfilAccion', array(
             'local' => 'id_perfil',
             'foreign' => 'id_perfil'));

        $this->hasMany('Usuario', array(
             'local' => 'id_perfil',
             'foreign' => 'id_perfil_reporte'));
    }
}