<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Proyecto', 'doctrine');

/**
 * BaseProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_proyecto
 * @property integer $id_pais
 * @property date $fecha_creacion
 * @property integer $id_creador
 * @property string $titulo
 * @property string $titulo_ing
 * @property integer $id_responsable_proy
 * @property integer $numero_contrato
 * @property integer $numero_contable
 * @property string $nombre_contrato
 * @property integer $id_responsable_cont
 * @property date $fecha_firma_contrato
 * @property string $sigla_contable
 * @property string $nombre_proyecto_resum
 * @property string $donante
 * @property string $contraparte
 * @property string $correo_contraparte
 * @property integer $duracion_proyecto
 * @property date $fecha_inicio
 * @property date $fecha_termino
 * @property date $fecha_avance_inf
 * @property date $fecha_fin_inf
 * @property integer $id_moneda
 * @property decimal $overhead_autorizado
 * @property decimal $monto_total
 * @property integer $monto_pago_remesa
 * @property date $fecha_pago_remesa
 * @property string $descr_proyecto
 * @property string $descr_proyecto_ing
 * @property string $objetivo
 * @property integer $id_estado_proyecto
 * @property string $folio
 * @property integer $id_grupo_proyecto
 * @property integer $id_pais_ejecuta
 * @property decimal $recupera_costo
 * @property string $frases_claves
 * @property integer $id_tipo_control_tec
 * @property integer $id_tipo_control_fin
 * @property GrupoProyecto $GrupoProyecto
 * @property EstadoProyecto $EstadoProyecto
 * @property Moneda $Moneda
 * @property Pais $Pais
 * @property Usuario $Creador
 * @property Usuario $ResponsableProyecto
 * @property Usuario $ResponsableCont
 * @property Doctrine_Collection $Bitacora
 * @property Doctrine_Collection $GastoPais
 * @property Doctrine_Collection $Inbox
 * @property Doctrine_Collection $InformeProyecto
 * @property Doctrine_Collection $OrdenPago
 * @property Doctrine_Collection $Presupuesto
 * @property Doctrine_Collection $ProyectoAmbito
 * @property Doctrine_Collection $ProyectoGrupo
 * @property TipoControlProyecto $TipoControlTec
 * @property TipoControlProyecto $TipoControlFin
 * @property Pais $PaisEjecuta
 * @property Doctrine_Collection $UsuariosProyectoGrupo
 * @property Proveedor $Proveedor
 * 
 * @method integer             getIdProyecto()            Returns the current record's "id_proyecto" value
 * @method integer             getIdPais()                Returns the current record's "id_pais" value
 * @method date                getFechaCreacion()         Returns the current record's "fecha_creacion" value
 * @method integer             getIdCreador()             Returns the current record's "id_creador" value
 * @method string              getTitulo()                Returns the current record's "titulo" value
 * @method string              getTituloIng()             Returns the current record's "titulo_ing" value
 * @method integer             getIdResponsableProy()     Returns the current record's "id_responsable_proy" value
 * @method integer             getNumeroContrato()        Returns the current record's "numero_contrato" value
 * @method integer             getNumeroContable()        Returns the current record's "numero_contable" value
 * @method string              getNombreContrato()        Returns the current record's "nombre_contrato" value
 * @method integer             getIdResponsableCont()     Returns the current record's "id_responsable_cont" value
 * @method date                getFechaFirmaContrato()    Returns the current record's "fecha_firma_contrato" value
 * @method string              getSiglaContable()         Returns the current record's "sigla_contable" value
 * @method string              getNombreProyectoResum()   Returns the current record's "nombre_proyecto_resum" value
 * @method string              getDonante()               Returns the current record's "donante" value
 * @method string              getContraparte()           Returns the current record's "contraparte" value
 * @method string              getCorreoContraparte()     Returns the current record's "correo_contraparte" value
 * @method integer             getDuracionProyecto()      Returns the current record's "duracion_proyecto" value
 * @method date                getFechaInicio()           Returns the current record's "fecha_inicio" value
 * @method date                getFechaTermino()          Returns the current record's "fecha_termino" value
 * @method date                getFechaAvanceInf()        Returns the current record's "fecha_avance_inf" value
 * @method date                getFechaFinInf()           Returns the current record's "fecha_fin_inf" value
 * @method integer             getIdMoneda()              Returns the current record's "id_moneda" value
 * @method decimal             getOverheadAutorizado()    Returns the current record's "overhead_autorizado" value
 * @method decimal             getMontoTotal()            Returns the current record's "monto_total" value
 * @method integer             getMontoPagoRemesa()       Returns the current record's "monto_pago_remesa" value
 * @method date                getFechaPagoRemesa()       Returns the current record's "fecha_pago_remesa" value
 * @method string              getDescrProyecto()         Returns the current record's "descr_proyecto" value
 * @method string              getDescrProyectoIng()      Returns the current record's "descr_proyecto_ing" value
 * @method string              getObjetivo()              Returns the current record's "objetivo" value
 * @method integer             getIdEstadoProyecto()      Returns the current record's "id_estado_proyecto" value
 * @method string              getFolio()                 Returns the current record's "folio" value
 * @method integer             getIdGrupoProyecto()       Returns the current record's "id_grupo_proyecto" value
 * @method integer             getIdPaisEjecuta()         Returns the current record's "id_pais_ejecuta" value
 * @method decimal             getRecuperaCosto()         Returns the current record's "recupera_costo" value
 * @method string              getFrasesClaves()          Returns the current record's "frases_claves" value
 * @method integer             getIdTipoControlTec()      Returns the current record's "id_tipo_control_tec" value
 * @method integer             getIdTipoControlFin()      Returns the current record's "id_tipo_control_fin" value
 * @method GrupoProyecto       getGrupoProyecto()         Returns the current record's "GrupoProyecto" value
 * @method EstadoProyecto      getEstadoProyecto()        Returns the current record's "EstadoProyecto" value
 * @method Moneda              getMoneda()                Returns the current record's "Moneda" value
 * @method Pais                getPais()                  Returns the current record's "Pais" value
 * @method Usuario             getCreador()               Returns the current record's "Creador" value
 * @method Usuario             getResponsableProyecto()   Returns the current record's "ResponsableProyecto" value
 * @method Usuario             getResponsableCont()       Returns the current record's "ResponsableCont" value
 * @method Doctrine_Collection getBitacora()              Returns the current record's "Bitacora" collection
 * @method Doctrine_Collection getGastoPais()             Returns the current record's "GastoPais" collection
 * @method Doctrine_Collection getInbox()                 Returns the current record's "Inbox" collection
 * @method Doctrine_Collection getInformeProyecto()       Returns the current record's "InformeProyecto" collection
 * @method Doctrine_Collection getOrdenPago()             Returns the current record's "OrdenPago" collection
 * @method Doctrine_Collection getPresupuesto()           Returns the current record's "Presupuesto" collection
 * @method Doctrine_Collection getProyectoAmbito()        Returns the current record's "ProyectoAmbito" collection
 * @method Doctrine_Collection getProyectoGrupo()         Returns the current record's "ProyectoGrupo" collection
 * @method TipoControlProyecto getTipoControlTec()        Returns the current record's "TipoControlTec" value
 * @method TipoControlProyecto getTipoControlFin()        Returns the current record's "TipoControlFin" value
 * @method Pais                getPaisEjecuta()           Returns the current record's "PaisEjecuta" value
 * @method Doctrine_Collection getUsuariosProyectoGrupo() Returns the current record's "UsuariosProyectoGrupo" collection
 * @method Proveedor           getProveedor()             Returns the current record's "Proveedor" value
 * @method Proyecto            setIdProyecto()            Sets the current record's "id_proyecto" value
 * @method Proyecto            setIdPais()                Sets the current record's "id_pais" value
 * @method Proyecto            setFechaCreacion()         Sets the current record's "fecha_creacion" value
 * @method Proyecto            setIdCreador()             Sets the current record's "id_creador" value
 * @method Proyecto            setTitulo()                Sets the current record's "titulo" value
 * @method Proyecto            setTituloIng()             Sets the current record's "titulo_ing" value
 * @method Proyecto            setIdResponsableProy()     Sets the current record's "id_responsable_proy" value
 * @method Proyecto            setNumeroContrato()        Sets the current record's "numero_contrato" value
 * @method Proyecto            setNumeroContable()        Sets the current record's "numero_contable" value
 * @method Proyecto            setNombreContrato()        Sets the current record's "nombre_contrato" value
 * @method Proyecto            setIdResponsableCont()     Sets the current record's "id_responsable_cont" value
 * @method Proyecto            setFechaFirmaContrato()    Sets the current record's "fecha_firma_contrato" value
 * @method Proyecto            setSiglaContable()         Sets the current record's "sigla_contable" value
 * @method Proyecto            setNombreProyectoResum()   Sets the current record's "nombre_proyecto_resum" value
 * @method Proyecto            setDonante()               Sets the current record's "donante" value
 * @method Proyecto            setContraparte()           Sets the current record's "contraparte" value
 * @method Proyecto            setCorreoContraparte()     Sets the current record's "correo_contraparte" value
 * @method Proyecto            setDuracionProyecto()      Sets the current record's "duracion_proyecto" value
 * @method Proyecto            setFechaInicio()           Sets the current record's "fecha_inicio" value
 * @method Proyecto            setFechaTermino()          Sets the current record's "fecha_termino" value
 * @method Proyecto            setFechaAvanceInf()        Sets the current record's "fecha_avance_inf" value
 * @method Proyecto            setFechaFinInf()           Sets the current record's "fecha_fin_inf" value
 * @method Proyecto            setIdMoneda()              Sets the current record's "id_moneda" value
 * @method Proyecto            setOverheadAutorizado()    Sets the current record's "overhead_autorizado" value
 * @method Proyecto            setMontoTotal()            Sets the current record's "monto_total" value
 * @method Proyecto            setMontoPagoRemesa()       Sets the current record's "monto_pago_remesa" value
 * @method Proyecto            setFechaPagoRemesa()       Sets the current record's "fecha_pago_remesa" value
 * @method Proyecto            setDescrProyecto()         Sets the current record's "descr_proyecto" value
 * @method Proyecto            setDescrProyectoIng()      Sets the current record's "descr_proyecto_ing" value
 * @method Proyecto            setObjetivo()              Sets the current record's "objetivo" value
 * @method Proyecto            setIdEstadoProyecto()      Sets the current record's "id_estado_proyecto" value
 * @method Proyecto            setFolio()                 Sets the current record's "folio" value
 * @method Proyecto            setIdGrupoProyecto()       Sets the current record's "id_grupo_proyecto" value
 * @method Proyecto            setIdPaisEjecuta()         Sets the current record's "id_pais_ejecuta" value
 * @method Proyecto            setRecuperaCosto()         Sets the current record's "recupera_costo" value
 * @method Proyecto            setFrasesClaves()          Sets the current record's "frases_claves" value
 * @method Proyecto            setIdTipoControlTec()      Sets the current record's "id_tipo_control_tec" value
 * @method Proyecto            setIdTipoControlFin()      Sets the current record's "id_tipo_control_fin" value
 * @method Proyecto            setGrupoProyecto()         Sets the current record's "GrupoProyecto" value
 * @method Proyecto            setEstadoProyecto()        Sets the current record's "EstadoProyecto" value
 * @method Proyecto            setMoneda()                Sets the current record's "Moneda" value
 * @method Proyecto            setPais()                  Sets the current record's "Pais" value
 * @method Proyecto            setCreador()               Sets the current record's "Creador" value
 * @method Proyecto            setResponsableProyecto()   Sets the current record's "ResponsableProyecto" value
 * @method Proyecto            setResponsableCont()       Sets the current record's "ResponsableCont" value
 * @method Proyecto            setBitacora()              Sets the current record's "Bitacora" collection
 * @method Proyecto            setGastoPais()             Sets the current record's "GastoPais" collection
 * @method Proyecto            setInbox()                 Sets the current record's "Inbox" collection
 * @method Proyecto            setInformeProyecto()       Sets the current record's "InformeProyecto" collection
 * @method Proyecto            setOrdenPago()             Sets the current record's "OrdenPago" collection
 * @method Proyecto            setPresupuesto()           Sets the current record's "Presupuesto" collection
 * @method Proyecto            setProyectoAmbito()        Sets the current record's "ProyectoAmbito" collection
 * @method Proyecto            setProyectoGrupo()         Sets the current record's "ProyectoGrupo" collection
 * @method Proyecto            setTipoControlTec()        Sets the current record's "TipoControlTec" value
 * @method Proyecto            setTipoControlFin()        Sets the current record's "TipoControlFin" value
 * @method Proyecto            setPaisEjecuta()           Sets the current record's "PaisEjecuta" value
 * @method Proyecto            setUsuariosProyectoGrupo() Sets the current record's "UsuariosProyectoGrupo" collection
 * @method Proyecto            setProveedor()             Sets the current record's "Proveedor" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proyecto');
        $this->hasColumn('id_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_creador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('titulo_ing', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_responsable_proy', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_contrato', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_contable', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre_contrato', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_responsable_cont', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_firma_contrato', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sigla_contable', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('nombre_proyecto_resum', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('donante', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('contraparte', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('correo_contraparte', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('duracion_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_termino', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_avance_inf', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_fin_inf', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_moneda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('overhead_autorizado', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('monto_total', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('monto_pago_remesa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_pago_remesa', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('descr_proyecto', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('descr_proyecto_ing', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('objetivo', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('id_estado_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('folio', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_grupo_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_pais_ejecuta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('recupera_costo', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('frases_claves', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_tipo_control_tec', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_control_fin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GrupoProyecto', array(
             'local' => 'id_grupo_proyecto',
             'foreign' => 'id_grupo_proyecto'));

        $this->hasOne('EstadoProyecto', array(
             'local' => 'id_estado_proyecto',
             'foreign' => 'id_estado_proyecto'));

        $this->hasOne('Moneda', array(
             'local' => 'id_moneda',
             'foreign' => 'id_moneda'));

        $this->hasOne('Pais', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));

        $this->hasOne('Usuario as Creador', array(
             'local' => 'id_creador',
             'foreign' => 'id_usuario'));

        $this->hasOne('Usuario as ResponsableProyecto', array(
             'local' => 'id_responsable_proy',
             'foreign' => 'id_usuario'));

        $this->hasOne('Usuario as ResponsableCont', array(
             'local' => 'id_responsable_cont',
             'foreign' => 'id_usuario'));

        $this->hasMany('Bitacora', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasMany('GastoPais', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasMany('Inbox', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasMany('InformeProyecto', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasMany('OrdenPago', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasMany('Presupuesto', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasMany('ProyectoAmbito', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasMany('ProyectoGrupo', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasOne('TipoControlProyecto as TipoControlTec', array(
             'local' => 'id_tipo_control_tec',
             'foreign' => 'id_tipo_control'));

        $this->hasOne('TipoControlProyecto as TipoControlFin', array(
             'local' => 'id_tipo_control_fin',
             'foreign' => 'id_tipo_control'));

        $this->hasOne('Pais as PaisEjecuta', array(
             'local' => 'id_pais_ejecuta',
             'foreign' => 'id_pais'));

        $this->hasMany('Usuario as UsuariosProyectoGrupo', array(
             'refClass' => 'ProyectoGrupo',
             'local' => 'id_proyecto',
             'foreign' => 'id_usuario'));

        $this->hasOne('Proveedor', array(
             'local' => 'rut_proveedor',
             'foreign' => 'rut_proveedor'));
    }
}