<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Bitacora', 'doctrine');

/**
 * BaseBitacora
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_bitacora
 * @property integer $id_proyecto
 * @property integer $id_usuario
 * @property integer $id_accion
 * @property date $fecha_creacion
 * @property string $observacion
 * @property Accion $Accion
 * @property Proyecto $Proyecto
 * @property Usuario $Usuario
 * 
 * @method integer  getIdBitacora()     Returns the current record's "id_bitacora" value
 * @method integer  getIdProyecto()     Returns the current record's "id_proyecto" value
 * @method integer  getIdUsuario()      Returns the current record's "id_usuario" value
 * @method integer  getIdAccion()       Returns the current record's "id_accion" value
 * @method date     getFechaCreacion()  Returns the current record's "fecha_creacion" value
 * @method string   getObservacion()    Returns the current record's "observacion" value
 * @method Accion   getAccion()         Returns the current record's "Accion" value
 * @method Proyecto getProyecto()       Returns the current record's "Proyecto" value
 * @method Usuario  getUsuario()        Returns the current record's "Usuario" value
 * @method Bitacora setIdBitacora()     Sets the current record's "id_bitacora" value
 * @method Bitacora setIdProyecto()     Sets the current record's "id_proyecto" value
 * @method Bitacora setIdUsuario()      Sets the current record's "id_usuario" value
 * @method Bitacora setIdAccion()       Sets the current record's "id_accion" value
 * @method Bitacora setFechaCreacion()  Sets the current record's "fecha_creacion" value
 * @method Bitacora setObservacion()    Sets the current record's "observacion" value
 * @method Bitacora setAccion()         Sets the current record's "Accion" value
 * @method Bitacora setProyecto()       Sets the current record's "Proyecto" value
 * @method Bitacora setUsuario()        Sets the current record's "Usuario" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBitacora extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bitacora');
        $this->hasColumn('id_bitacora', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_accion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('observacion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Accion', array(
             'local' => 'id_accion',
             'foreign' => 'id_accion'));

        $this->hasOne('Proyecto', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario'));
    }
}