<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GastoPais', 'doctrine');

/**
 * BaseGastoPais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_gasto_pais
 * @property integer $id_proyecto
 * @property integer $id_tipo_movimiento
 * @property integer $id_archivo_gasto_pais
 * @property string $cuenta
 * @property string $nombre_cuenta
 * @property string $periodo
 * @property integer $enero
 * @property integer $febrero
 * @property integer $marzo
 * @property integer $abril
 * @property integer $mayo
 * @property integer $junio
 * @property integer $julio
 * @property integer $agosto
 * @property integer $septiembre
 * @property integer $octubre
 * @property integer $noviembre
 * @property integer $diciembre
 * @property ArchivoGastoPais $ArchivoGastoPais
 * @property Proyecto $Proyecto
 * @property TipoMovimiento $TipoMovimiento
 * 
 * @method integer          getIdGastoPais()           Returns the current record's "id_gasto_pais" value
 * @method integer          getIdProyecto()            Returns the current record's "id_proyecto" value
 * @method integer          getIdTipoMovimiento()      Returns the current record's "id_tipo_movimiento" value
 * @method integer          getIdArchivoGastoPais()    Returns the current record's "id_archivo_gasto_pais" value
 * @method string           getCuenta()                Returns the current record's "cuenta" value
 * @method string           getNombreCuenta()          Returns the current record's "nombre_cuenta" value
 * @method string           getPeriodo()               Returns the current record's "periodo" value
 * @method integer          getEnero()                 Returns the current record's "enero" value
 * @method integer          getFebrero()               Returns the current record's "febrero" value
 * @method integer          getMarzo()                 Returns the current record's "marzo" value
 * @method integer          getAbril()                 Returns the current record's "abril" value
 * @method integer          getMayo()                  Returns the current record's "mayo" value
 * @method integer          getJunio()                 Returns the current record's "junio" value
 * @method integer          getJulio()                 Returns the current record's "julio" value
 * @method integer          getAgosto()                Returns the current record's "agosto" value
 * @method integer          getSeptiembre()            Returns the current record's "septiembre" value
 * @method integer          getOctubre()               Returns the current record's "octubre" value
 * @method integer          getNoviembre()             Returns the current record's "noviembre" value
 * @method integer          getDiciembre()             Returns the current record's "diciembre" value
 * @method ArchivoGastoPais getArchivoGastoPais()      Returns the current record's "ArchivoGastoPais" value
 * @method Proyecto         getProyecto()              Returns the current record's "Proyecto" value
 * @method TipoMovimiento   getTipoMovimiento()        Returns the current record's "TipoMovimiento" value
 * @method GastoPais        setIdGastoPais()           Sets the current record's "id_gasto_pais" value
 * @method GastoPais        setIdProyecto()            Sets the current record's "id_proyecto" value
 * @method GastoPais        setIdTipoMovimiento()      Sets the current record's "id_tipo_movimiento" value
 * @method GastoPais        setIdArchivoGastoPais()    Sets the current record's "id_archivo_gasto_pais" value
 * @method GastoPais        setCuenta()                Sets the current record's "cuenta" value
 * @method GastoPais        setNombreCuenta()          Sets the current record's "nombre_cuenta" value
 * @method GastoPais        setPeriodo()               Sets the current record's "periodo" value
 * @method GastoPais        setEnero()                 Sets the current record's "enero" value
 * @method GastoPais        setFebrero()               Sets the current record's "febrero" value
 * @method GastoPais        setMarzo()                 Sets the current record's "marzo" value
 * @method GastoPais        setAbril()                 Sets the current record's "abril" value
 * @method GastoPais        setMayo()                  Sets the current record's "mayo" value
 * @method GastoPais        setJunio()                 Sets the current record's "junio" value
 * @method GastoPais        setJulio()                 Sets the current record's "julio" value
 * @method GastoPais        setAgosto()                Sets the current record's "agosto" value
 * @method GastoPais        setSeptiembre()            Sets the current record's "septiembre" value
 * @method GastoPais        setOctubre()               Sets the current record's "octubre" value
 * @method GastoPais        setNoviembre()             Sets the current record's "noviembre" value
 * @method GastoPais        setDiciembre()             Sets the current record's "diciembre" value
 * @method GastoPais        setArchivoGastoPais()      Sets the current record's "ArchivoGastoPais" value
 * @method GastoPais        setProyecto()              Sets the current record's "Proyecto" value
 * @method GastoPais        setTipoMovimiento()        Sets the current record's "TipoMovimiento" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGastoPais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gasto_pais');
        $this->hasColumn('id_gasto_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_movimiento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_archivo_gasto_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cuenta', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('nombre_cuenta', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('periodo', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('enero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('febrero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('marzo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('abril', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mayo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('junio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('julio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('agosto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('septiembre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('octubre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('noviembre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('diciembre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ArchivoGastoPais', array(
             'local' => 'id_archivo_gasto_pais',
             'foreign' => 'id_archivo_gasto_pais'));

        $this->hasOne('Proyecto', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasOne('TipoMovimiento', array(
             'local' => 'id_tipo_movimiento',
             'foreign' => 'id_tipo_movimiento'));
    }
}