<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProyectoRespaldo', 'doctrine');

/**
 * BaseProyectoRespaldo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_proyecto
 * @property integer $id_pais
 * @property date $fecha_creacion
 * @property integer $id_creador
 * @property string $titulo
 * @property string $titulo_ing
 * @property integer $id_responsable_proy
 * @property integer $numero_contrato
 * @property integer $numero_contable
 * @property string $nombre_contrato
 * @property integer $id_responsable_cont
 * @property date $fecha_firma_contrato
 * @property string $sigla_contable
 * @property string $nombre_proyecto_resum
 * @property string $donante
 * @property string $contraparte
 * @property string $correo_contraparte
 * @property integer $duracion_proyecto
 * @property date $fecha_inicio
 * @property date $fecha_termino
 * @property date $fecha_avance_inf
 * @property date $fecha_fin_inf
 * @property integer $id_moneda
 * @property integer $overhead_autorizado
 * @property integer $monto_total
 * @property integer $monto_pago_remesa
 * @property date $fecha_pago_remesa
 * @property string $descr_proyecto
 * @property string $descr_proyecto_ing
 * @property string $objetivo
 * @property integer $id_estado_proyecto
 * @property integer $id_padre
 * @property Doctrine_Collection $PresupuestoRespaldo
 * 
 * @method integer             getIdProyecto()            Returns the current record's "id_proyecto" value
 * @method integer             getIdPais()                Returns the current record's "id_pais" value
 * @method date                getFechaCreacion()         Returns the current record's "fecha_creacion" value
 * @method integer             getIdCreador()             Returns the current record's "id_creador" value
 * @method string              getTitulo()                Returns the current record's "titulo" value
 * @method string              getTituloIng()             Returns the current record's "titulo_ing" value
 * @method integer             getIdResponsableProy()     Returns the current record's "id_responsable_proy" value
 * @method integer             getNumeroContrato()        Returns the current record's "numero_contrato" value
 * @method integer             getNumeroContable()        Returns the current record's "numero_contable" value
 * @method string              getNombreContrato()        Returns the current record's "nombre_contrato" value
 * @method integer             getIdResponsableCont()     Returns the current record's "id_responsable_cont" value
 * @method date                getFechaFirmaContrato()    Returns the current record's "fecha_firma_contrato" value
 * @method string              getSiglaContable()         Returns the current record's "sigla_contable" value
 * @method string              getNombreProyectoResum()   Returns the current record's "nombre_proyecto_resum" value
 * @method string              getDonante()               Returns the current record's "donante" value
 * @method string              getContraparte()           Returns the current record's "contraparte" value
 * @method string              getCorreoContraparte()     Returns the current record's "correo_contraparte" value
 * @method integer             getDuracionProyecto()      Returns the current record's "duracion_proyecto" value
 * @method date                getFechaInicio()           Returns the current record's "fecha_inicio" value
 * @method date                getFechaTermino()          Returns the current record's "fecha_termino" value
 * @method date                getFechaAvanceInf()        Returns the current record's "fecha_avance_inf" value
 * @method date                getFechaFinInf()           Returns the current record's "fecha_fin_inf" value
 * @method integer             getIdMoneda()              Returns the current record's "id_moneda" value
 * @method integer             getOverheadAutorizado()    Returns the current record's "overhead_autorizado" value
 * @method integer             getMontoTotal()            Returns the current record's "monto_total" value
 * @method integer             getMontoPagoRemesa()       Returns the current record's "monto_pago_remesa" value
 * @method date                getFechaPagoRemesa()       Returns the current record's "fecha_pago_remesa" value
 * @method string              getDescrProyecto()         Returns the current record's "descr_proyecto" value
 * @method string              getDescrProyectoIng()      Returns the current record's "descr_proyecto_ing" value
 * @method string              getObjetivo()              Returns the current record's "objetivo" value
 * @method integer             getIdEstadoProyecto()      Returns the current record's "id_estado_proyecto" value
 * @method integer             getIdPadre()               Returns the current record's "id_padre" value
 * @method Doctrine_Collection getPresupuestoRespaldo()   Returns the current record's "PresupuestoRespaldo" collection
 * @method ProyectoRespaldo    setIdProyecto()            Sets the current record's "id_proyecto" value
 * @method ProyectoRespaldo    setIdPais()                Sets the current record's "id_pais" value
 * @method ProyectoRespaldo    setFechaCreacion()         Sets the current record's "fecha_creacion" value
 * @method ProyectoRespaldo    setIdCreador()             Sets the current record's "id_creador" value
 * @method ProyectoRespaldo    setTitulo()                Sets the current record's "titulo" value
 * @method ProyectoRespaldo    setTituloIng()             Sets the current record's "titulo_ing" value
 * @method ProyectoRespaldo    setIdResponsableProy()     Sets the current record's "id_responsable_proy" value
 * @method ProyectoRespaldo    setNumeroContrato()        Sets the current record's "numero_contrato" value
 * @method ProyectoRespaldo    setNumeroContable()        Sets the current record's "numero_contable" value
 * @method ProyectoRespaldo    setNombreContrato()        Sets the current record's "nombre_contrato" value
 * @method ProyectoRespaldo    setIdResponsableCont()     Sets the current record's "id_responsable_cont" value
 * @method ProyectoRespaldo    setFechaFirmaContrato()    Sets the current record's "fecha_firma_contrato" value
 * @method ProyectoRespaldo    setSiglaContable()         Sets the current record's "sigla_contable" value
 * @method ProyectoRespaldo    setNombreProyectoResum()   Sets the current record's "nombre_proyecto_resum" value
 * @method ProyectoRespaldo    setDonante()               Sets the current record's "donante" value
 * @method ProyectoRespaldo    setContraparte()           Sets the current record's "contraparte" value
 * @method ProyectoRespaldo    setCorreoContraparte()     Sets the current record's "correo_contraparte" value
 * @method ProyectoRespaldo    setDuracionProyecto()      Sets the current record's "duracion_proyecto" value
 * @method ProyectoRespaldo    setFechaInicio()           Sets the current record's "fecha_inicio" value
 * @method ProyectoRespaldo    setFechaTermino()          Sets the current record's "fecha_termino" value
 * @method ProyectoRespaldo    setFechaAvanceInf()        Sets the current record's "fecha_avance_inf" value
 * @method ProyectoRespaldo    setFechaFinInf()           Sets the current record's "fecha_fin_inf" value
 * @method ProyectoRespaldo    setIdMoneda()              Sets the current record's "id_moneda" value
 * @method ProyectoRespaldo    setOverheadAutorizado()    Sets the current record's "overhead_autorizado" value
 * @method ProyectoRespaldo    setMontoTotal()            Sets the current record's "monto_total" value
 * @method ProyectoRespaldo    setMontoPagoRemesa()       Sets the current record's "monto_pago_remesa" value
 * @method ProyectoRespaldo    setFechaPagoRemesa()       Sets the current record's "fecha_pago_remesa" value
 * @method ProyectoRespaldo    setDescrProyecto()         Sets the current record's "descr_proyecto" value
 * @method ProyectoRespaldo    setDescrProyectoIng()      Sets the current record's "descr_proyecto_ing" value
 * @method ProyectoRespaldo    setObjetivo()              Sets the current record's "objetivo" value
 * @method ProyectoRespaldo    setIdEstadoProyecto()      Sets the current record's "id_estado_proyecto" value
 * @method ProyectoRespaldo    setIdPadre()               Sets the current record's "id_padre" value
 * @method ProyectoRespaldo    setPresupuestoRespaldo()   Sets the current record's "PresupuestoRespaldo" collection
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProyectoRespaldo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proyecto_respaldo');
        $this->hasColumn('id_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_creador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('titulo_ing', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_responsable_proy', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_contrato', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_contable', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre_contrato', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_responsable_cont', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_firma_contrato', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sigla_contable', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('nombre_proyecto_resum', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('donante', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('contraparte', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('correo_contraparte', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('duracion_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_termino', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_avance_inf', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_fin_inf', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_moneda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('overhead_autorizado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monto_total', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monto_pago_remesa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_pago_remesa', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('descr_proyecto', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('descr_proyecto_ing', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('objetivo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_estado_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_padre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PresupuestoRespaldo', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));
    }
}