<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Territorio', 'doctrine');

/**
 * BaseTerritorio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_territorio
 * @property string $codigo
 * @property string $descripcion
 * @property Doctrine_Collection $PaisTerritorio
 * 
 * @method integer             getIdTerritorio()   Returns the current record's "id_territorio" value
 * @method string              getCodigo()         Returns the current record's "codigo" value
 * @method string              getDescripcion()    Returns the current record's "descripcion" value
 * @method Doctrine_Collection getPaisTerritorio() Returns the current record's "PaisTerritorio" collection
 * @method Territorio          setIdTerritorio()   Sets the current record's "id_territorio" value
 * @method Territorio          setCodigo()         Sets the current record's "codigo" value
 * @method Territorio          setDescripcion()    Sets the current record's "descripcion" value
 * @method Territorio          setPaisTerritorio() Sets the current record's "PaisTerritorio" collection
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTerritorio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('territorio');
        $this->hasColumn('id_territorio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('descripcion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PaisTerritorio', array(
             'local' => 'id_territorio',
             'foreign' => 'id_territorio'));
    }
}