<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProyectoGrupo', 'doctrine');

/**
 * BaseProyectoGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_proyecto
 * @property integer $id_grupo_proyecto
 * @property integer $id_usuario
 * @property GrupoProyecto $GrupoProyecto
 * @property Proyecto $Proyecto
 * @property Usuario $Usuario
 * 
 * @method integer       getIdProyecto()        Returns the current record's "id_proyecto" value
 * @method integer       getIdGrupoProyecto()   Returns the current record's "id_grupo_proyecto" value
 * @method integer       getIdUsuario()         Returns the current record's "id_usuario" value
 * @method GrupoProyecto getGrupoProyecto()     Returns the current record's "GrupoProyecto" value
 * @method Proyecto      getProyecto()          Returns the current record's "Proyecto" value
 * @method Usuario       getUsuario()           Returns the current record's "Usuario" value
 * @method ProyectoGrupo setIdProyecto()        Sets the current record's "id_proyecto" value
 * @method ProyectoGrupo setIdGrupoProyecto()   Sets the current record's "id_grupo_proyecto" value
 * @method ProyectoGrupo setIdUsuario()         Sets the current record's "id_usuario" value
 * @method ProyectoGrupo setGrupoProyecto()     Sets the current record's "GrupoProyecto" value
 * @method ProyectoGrupo setProyecto()          Sets the current record's "Proyecto" value
 * @method ProyectoGrupo setUsuario()           Sets the current record's "Usuario" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProyectoGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proyecto_grupo');
        $this->hasColumn('id_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_grupo_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GrupoProyecto', array(
             'local' => 'id_grupo_proyecto',
             'foreign' => 'id_grupo_proyecto'));

        $this->hasOne('Proyecto', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario'));
    }
}