<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pais', 'doctrine');

/**
 * BasePais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pais
 * @property string $codigo
 * @property string $descripcion
 * @property Doctrine_Collection $PaisTerritorio
 * @property Doctrine_Collection $Proyecto
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getIdPais()         Returns the current record's "id_pais" value
 * @method string              getCodigo()         Returns the current record's "codigo" value
 * @method string              getDescripcion()    Returns the current record's "descripcion" value
 * @method Doctrine_Collection getPaisTerritorio() Returns the current record's "PaisTerritorio" collection
 * @method Doctrine_Collection getProyecto()       Returns the current record's "Proyecto" collection
 * @method Doctrine_Collection getUsuario()        Returns the current record's "Usuario" collection
 * @method Pais                setIdPais()         Sets the current record's "id_pais" value
 * @method Pais                setCodigo()         Sets the current record's "codigo" value
 * @method Pais                setDescripcion()    Sets the current record's "descripcion" value
 * @method Pais                setPaisTerritorio() Sets the current record's "PaisTerritorio" collection
 * @method Pais                setProyecto()       Sets the current record's "Proyecto" collection
 * @method Pais                setUsuario()        Sets the current record's "Usuario" collection
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pais');
        $this->hasColumn('id_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('descripcion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PaisTerritorio', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));

        $this->hasMany('Proyecto', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));

        $this->hasMany('Usuario', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));
    }
}