<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InformeProyecto', 'doctrine');

/**
 * BaseInformeProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_informe_proyecto
 * @property integer $id_proyecto
 * @property date $fecha_avance_inf
 * @property integer $numero
 * @property Proyecto $Proyecto
 * 
 * @method integer         getIdInformeProyecto()   Returns the current record's "id_informe_proyecto" value
 * @method integer         getIdProyecto()          Returns the current record's "id_proyecto" value
 * @method date            getFechaAvanceInf()      Returns the current record's "fecha_avance_inf" value
 * @method integer         getNumero()              Returns the current record's "numero" value
 * @method Proyecto        getProyecto()            Returns the current record's "Proyecto" value
 * @method InformeProyecto setIdInformeProyecto()   Sets the current record's "id_informe_proyecto" value
 * @method InformeProyecto setIdProyecto()          Sets the current record's "id_proyecto" value
 * @method InformeProyecto setFechaAvanceInf()      Sets the current record's "fecha_avance_inf" value
 * @method InformeProyecto setNumero()              Sets the current record's "numero" value
 * @method InformeProyecto setProyecto()            Sets the current record's "Proyecto" value
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInformeProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('informe_proyecto');
        $this->hasColumn('id_informe_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_proyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_avance_inf', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('numero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto', array(
             'local' => 'id_proyecto',
             'foreign' => 'id_proyecto'));
    }
}