<?php

/**
 * Accion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Accion extends BaseAccion
{
    const CREAR = 4;
    const APROBAR = 1;
    const CONTABILIZAR = 2;
    const MANTENER = 3;
    const OFICINA = 5;
    const VISUALIZAR = 6;

    public function __toString()
    {
        return $this->getNombre();
    }
}