<?php

/**
 * AccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Accion');
    }
}