<?php

/**
 * AmbitoTematicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AmbitoTematicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AmbitoTematicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AmbitoTematico');
    }
}