<?php

/**
 * ArchivoContratoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivoContratoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchivoContratoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArchivoContrato');
    }
}