<?php

/**
 * ArchivoOrdenPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArchivoOrdenPago extends BaseArchivoOrdenPago
{

    public function save(Doctrine_Connection $conn = null)
    {
        $this->setArchivo(trim($this->getArchivo()));
        if($this->getArchivo())
        {
            return parent::save();
        }else {
            return null;
        }
    }
}