<?php

/**
 * ArchivosAdjuntosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivosAdjuntosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchivosAdjuntosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArchivosAdjuntos');
    }
}