<?php

/**
 * DetalleOrdenPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleOrdenPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleOrdenPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleOrdenPago');
    }
}