<?php

/**
 * EstadoProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EstadoProyecto extends BaseEstadoProyecto
{
    const POR_APROBAR = 1;
    const APROBADO = 2;
    const POR_CONTABILIZAR = 3;
    const CONTABILIZADO = 4;
    
    public function __toString()
    {
        return $this->getDescripcion();
    }
}