<?php

/**
 * EstadoProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoProyecto');
    }
}