<?php

/**
 * FolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FolioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Folio');
    }
}