<?php

/**
 * GastoPaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GastoPaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GastoPaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GastoPais');
    }
}