<?php

/**
 * GrupoProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrupoProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrupoProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GrupoProyecto');
    }
}