<?php

/**
 * InformeProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InformeProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InformeProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InformeProyecto');
    }
}