<?php

/**
 * Moneda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Moneda extends BaseMoneda
{
    const CLP = 1;
    const USD = 2;
    const COB = 3;
    const MX = 4;
    const PY = 5;
    
    public function __toString()
    {
        return $this->getDescripcion();
    }
}