<?php

/**
 * MonedaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MonedaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MonedaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Moneda');
    }
}