<?php

/**
 * OrdenPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenPago');
    }
}