<?php

/**
 * PerfilAccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerfilAccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerfilAccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerfilAccion');
    }
}