<?php

/**
 * PresupuestoRespaldoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PresupuestoRespaldoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PresupuestoRespaldoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PresupuestoRespaldo');
    }
}