<?php

/**
 * Presupuesto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Presupuesto extends BasePresupuesto
{
    public function getTotal()
    {
        $total = $this->getEnero() + $this->getFebrero() + $this->getMarzo() + $this->getAbril() + $this->getMayo() + $this->getJunio() + $this->getJulio() + $this->getAgosto() + + $this->getSeptiembre() + $this->getOctubre() + $this->getNoviembre() + $this->getDiciembre();
        return $total;
    }
}