<?php

/**
 * ProyectoRespaldoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectoRespaldoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectoRespaldoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProyectoRespaldo');
    }
}