<?php

/**
 * Proyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Proyecto extends BaseProyecto
{
    public function __toString()
    {
        return $this->getNumeroContable()." - ".$this->getSiglaContable();
    }

    public function saveRespaldo()
    {
        $idProyecto = $this->getIdProyecto();
        $proyectoRespaldo = new ProyectoRespaldo();
        $proyectoRespaldo->setIdPais($this->getIdPais());
        $proyectoRespaldo->setFechaCreacion($this->getFechaCreacion());
        $proyectoRespaldo->setIdCreador($this->getIdCreador());
        $proyectoRespaldo->setTitulo($this->getTitulo());
        $proyectoRespaldo->setTituloIng($this->getTituloIng());
        $proyectoRespaldo->setIdResponsableProy($this->getIdResponsableProy());
        $proyectoRespaldo->setNumeroContrato($this->getNumeroContrato());
        $proyectoRespaldo->setNumeroContable($this->getNumeroContable());
        $proyectoRespaldo->setNombreContrato($this->getNombreContrato());
        $proyectoRespaldo->setIdResponsableCont($this->getIdResponsableCont());
        $proyectoRespaldo->setFechaFirmaContrato($this->getFechaFirmaContrato());
        $proyectoRespaldo->setSiglaContable($this->getSiglaContable());
        $proyectoRespaldo->setNombreProyectoResum($this->getNombreProyectoResum());
        $proyectoRespaldo->setDonante($this->getDonante());
        $proyectoRespaldo->setContraparte($this->getContraparte());
        $proyectoRespaldo->setCorreoContraparte($this->getCorreoContraparte());
        $proyectoRespaldo->setDuracionProyecto($this->getDuracionProyecto());
        $proyectoRespaldo->setFechaInicio($this->getFechaInicio());
        $proyectoRespaldo->setFechaTermino($this->getFechaTermino());
        $proyectoRespaldo->setFechaAvanceInf($this->getFechaAvanceInf());
        $proyectoRespaldo->setFechaFinInf($this->getFechaFinInf());
        $proyectoRespaldo->setIdMoneda($this->getIdMoneda());
        $proyectoRespaldo->setOverheadAutorizado($this->getOverheadAutorizado());
        $proyectoRespaldo->setMontoTotal($this->getMontoTotal());
        $proyectoRespaldo->setDescrProyecto($this->getDescrProyecto());
        $proyectoRespaldo->setDescrProyectoIng($this->getDescrProyectoIng());
        $proyectoRespaldo->setObjetivo($this->getObjetivo());
        $proyectoRespaldo->setIdEstadoProyecto($this->getIdEstadoProyecto());
        $proyectoRespaldo->setIdPadre($idProyecto);
        $proyectoRespaldo->save();

        $idProyectoRespaldo = $proyectoRespaldo->getIncremented();

        $query = "INSERT INTO presupuesto_respaldo(cuenta,nombre_cuenta,periodo,id_tipo_movimiento,id_proyecto,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre) 
                    SELECT cuenta,nombre_cuenta,periodo,id_tipo_movimiento,$idProyectoRespaldo,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre FROM presupuesto WHERE id_proyecto = $idProyecto";
        $con = Doctrine_Manager::getInstance()->getCurrentConnection();
        $st = $con->execute($query);
        return $st;
    }

    public function getReporteDetalle()
    {
        $response = ProyectoTable::getInstance()->getReporteDetalle($this->getIdProyecto());
        return $response;
    }
}