<?php

/**
 * ProyectoAmbitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectoAmbitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectoAmbitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProyectoAmbito');
    }
}