<?php

/**
 * ProyectoGrupoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectoGrupoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectoGrupoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProyectoGrupo');
    }
}