<?php

/**
 * RptGeneralProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RptGeneralProyecto extends BaseRptGeneralProyecto
{
    public static function poblarReporteGeneralProyecto()
    {
        return RptGeneralProyectoTable::getInstance()->poblarReporteGeneralProyecto();
    }

}