<?php

/**
 * TerritorioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TerritorioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TerritorioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Territorio');
    }
}