<?php

/**
 * TipoMovimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigpro
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TipoMovimiento extends BaseTipoMovimiento
{
    const INGRESO = 1;
    const EGRESO = 2;
    
    public function __toString()
    {
        return $this->getDescripcion();
    }
}