<?php

/**
 * TipoControlProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoControlProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoControlProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoControlProyecto');
    }
}