<?php

/**
 * TipoMovimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoMovimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoMovimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoMovimiento');
    }
}