# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    #robots:       index, follow

  stylesheets:    [main.css,/assets/bootstrap/css/bootstrap.min.css,/assets/bower_components/metisMenu/dist/metisMenu.min.css,/assets/css/css_table.css,/assets/sb-admin/css/sb-admin-2.css,https://fonts.googleapis.com/css?family=Roboto+Condensed,/assets/css/filer/jquery.filer.css,/assets/bower_components/font-awesome/css/font-awesome.min.css,/assets/bootstrap-datetimepicker-master/build/css/bootstrap-datetimepicker.min.css,/assets/css/blueimp-gallery.min.css,easy_paginate,/assets/select2-master/dist/css/select2.min.css]
  javascripts:    [jquery, main, /assets/bootstrap/js/bootstrap.min.js,/assets/bower_components/metisMenu/dist/metisMenu.min.js,/assets/bower_components/moment/min/moment.min.js,/assets/bower_components/moment/locale/es.js,/assets/bootstrap-datetimepicker-master/build/js/bootstrap-datetimepicker.min.js,/assets/bootstrap-maxlength/src/bootstrap-maxlength.js,/assets/select2-master/dist/js/select2.full.js,/assets/js/easyPaginate/lib/easyPaginate.js, /assets/bower_components/metisMenu/dist/metisMenu.min.js, /assets/sb-admin/js/sb-admin-2.js]

  has_layout:     true
  layout:         layout

loginSuccess:
    javascripts:    []
    stylesheets: [-*,/assets/css/rimisp.css,/assets/bootstrap/css/bootstrap.min.css,/assets/css/jumbotron.css,/assets/css/ie10-viewport-bug-workaround.css]
    has_layout: false

ingresoProyectoSuccess:
    javascripts:    [/izarusBootstrapPlugin/js/bootstrap-components.js, ingresoProyectos, /DataTables/datatables.min.js ]
    stylesheets: [/izarusBootstrapPlugin/css/bootstrap-components.css,/DataTables/datatables.min.css]
#    javascripts:    [/izarusBootstrapPlugin/js/bootstrap-components.js, ingresoProyectos,/DataTables/datatables.js, /DataTables/Responsive-2.1.1/js/dataTables.responsive.js,/DataTables/Responsive-2.1.1/js/responsive.bootstrap.js,/DataTables/FixedHeader-3.1.2/js/dataTables.fixedHeader.js,/DataTables/Select-1.2.2/js/dataTables.select.js,/DataTables/Buttons-1.3.1/js/buttons.bootstrap.js]
#    stylesheets: [/izarusBootstrapPlugin/css/bootstrap-components.css,/DataTables/dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.bootstrap.css,/DataTables/FixedHeader-3.1.2/css/fixedHeader.dataTables.css]

ordenPagoSuccess:
    javascripts: []
    stylesheets: []

#reporteInformesSuccess:
#    javascripts: [/DataTables/datatables.js, /DataTables/Responsive-2.1.1/js/dataTables.responsive.js,/DataTables/Responsive-2.1.1/js/responsive.bootstrap.js,/DataTables/FixedHeader-3.1.2/js/dataTables.fixedHeader.js,/DataTables/Select-1.2.2/js/dataTables.select.js,/DataTables/Buttons-1.3.1/js/buttons.bootstrap.js]
#    stylesheets: [/DataTables/dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.bootstrap.css,/DataTables/FixedHeader-3.1.2/css/fixedHeader.dataTables.css]
reporteInformesSuccess:
#    javascripts: [https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/jquery.dataTables.min.js,https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/dataTables.bootstrap.min.js]
#    stylesheets: [https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/css/dataTables.bootstrap.min.css]
    javascripts: [/DataTables/datatables.min.js]
    stylesheets: [/DataTables/datatables.min.css]

reporteInformeDetalleSuccess:
    javascripts: [https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/jquery.dataTables.min.js,https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/dataTables.bootstrap.min.js]
    stylesheets: [https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/css/dataTables.bootstrap.min.css]
#    javascripts: [/DataTables/datatables.js, /DataTables/Responsive-2.1.1/js/dataTables.responsive.js,/DataTables/Responsive-2.1.1/js/responsive.bootstrap.js,/DataTables/FixedHeader-3.1.2/js/dataTables.fixedHeader.js,/DataTables/Select-1.2.2/js/dataTables.select.js,/DataTables/Buttons-1.3.1/js/buttons.bootstrap.js]
#    stylesheets: [/DataTables/dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.bootstrap.css,/DataTables/FixedHeader-3.1.2/css/fixedHeader.dataTables.css]

reporteInformeDetalleTotalSuccess:
    javascripts: [https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/jquery.dataTables.min.js,https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/dataTables.bootstrap.min.js]
    stylesheets: [https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/css/dataTables.bootstrap.min.css]
#    javascripts: [/DataTables/datatables.js, /DataTables/Responsive-2.1.1/js/dataTables.responsive.js,/DataTables/Responsive-2.1.1/js/responsive.bootstrap.js,/DataTables/FixedHeader-3.1.2/js/dataTables.fixedHeader.js,/DataTables/Select-1.2.2/js/dataTables.select.js,/DataTables/Buttons-1.3.1/js/buttons.bootstrap.js]
#    stylesheets: [/DataTables/dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.bootstrap.css,/DataTables/FixedHeader-3.1.2/css/fixedHeader.dataTables.css]

gastoPaisSuccess:
    javascripts: [https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/jquery.dataTables.min.js,https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/js/dataTables.bootstrap.min.js]
    stylesheets: [https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.15/css/dataTables.bootstrap.min.css]
#    javascripts: [/DataTables/datatables.js, /DataTables/Responsive-2.1.1/js/dataTables.responsive.js,/DataTables/Responsive-2.1.1/js/responsive.bootstrap.js,/DataTables/FixedHeader-3.1.2/js/dataTables.fixedHeader.js,/DataTables/Select-1.2.2/js/dataTables.select.js,/DataTables/Buttons-1.3.1/js/buttons.bootstrap.js]
#    stylesheets: [/DataTables/dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.dataTables.css,/DataTables/Responsive-2.1.1/css/responsive.bootstrap.css,/DataTables/FixedHeader-3.1.2/css/fixedHeader.dataTables.css]